In [ ]:
import os
import sys
from pathlib import Path
if os.getcwd().endswith('analysis'):
    ROOT = Path('..').absolute()
else:
    ROOT = Path('.').absolute()
os.chdir(ROOT)
sys.path.append(str(ROOT))
print(os.getcwd())

c:\Users\YuMeow\WorkSpace\42-MySRAgent

In [2]:
import json
import pandas as pd

# save_dir = Path('logs/bench_sr_agent/bench_my_sr_agent')
for save_dir in [
    Path('logs/bench_sr_agent/bench_my_sr_agent-v4-flash'),
    Path('logs/bench_sr_agent/bench_my_sr_agent_deepseek-v4-pro'),
]:
    if True: # Load df_results
        df_list = []
        for exp_path in sorted((save_dir / "results").glob('*.jsonl'), key=lambda x: x.stem):
            lines = [json.loads(line) for line in exp_path.read_text(encoding="utf-8").splitlines() if line.strip()]
            successful_lines = [line for line in lines if 'error' not in line]
            result = successful_lines[-1] if successful_lines else lines[-1]
            df_list.append(result)
        df_results = pd.DataFrame(df_list)

        df_id = pd.DataFrame(df_results.pop('id_metrics').tolist(), index=df_results.index).add_prefix('id_')
        df_results = df_results.join(df_id)

        df_ood = pd.DataFrame(df_results.pop('ood_metrics').tolist(), index=df_results.index).add_prefix('ood_')
        df_results = df_results.join(df_ood)
        display(df_results)

    if True: # Load df_details
        df_list = []
        for exp_path in sorted((save_dir / "experiments").glob('*/result.jsonl'), key=lambda x: x.stem):
            dirname = exp_path.parent.name
            detail = json.loads(exp_path.read_text(encoding="utf-8").strip())
            detail['dirname'] = dirname
            df_list.append(detail)
        df_details = pd.DataFrame(df_list)
        # df_details['token_usage'] = df_details['token_usage'].str.removesuffix('token').str.replace(' k', 'e3').map(float)
        # df_details['money_usage'] = df_details['money_usage'].str.removesuffix('$').str.replace(' m', 'e-3').str.replace(' μ', 'e-6').map(float)
        df_details['token_usage'] = df_details['token_usage']
        df_details['money_usage'] = df_details['money_usage']
        display(df_details)

    if True: # Load df_tool_calls
        df_list = []
        for exp_path in sorted((save_dir / "experiments").glob('*/tool_calls.jsonl'), key=lambda x: x.stem):
            dirname = exp_path.parent.name
            tool_calls = [json.loads(line) for line in exp_path.read_text(encoding="utf-8").splitlines() if line.strip()]
            for call in tool_calls:
                call['dirname'] = dirname
            df_list.extend(tool_calls)
        df_tool_calls = pd.DataFrame(df_list)
        display(df_tool_calls)
    
    if True: # Display
        print(save_dir)
        display(df_details['status'].value_counts())
        display(df_details[['token_usage', 'money_usage']].agg(['mean', 'sum']))
        display(df_results['symbolic_acc'].agg(['mean', 'count', 'sum']).to_frame())

,equation_id,dataset_identifier,gt_expression,discovered_expression,num_train,num_test,search_time,symbolic_acc,symbolic_acc_detail,error,id_mse,id_nmse,id_r2,id_acc01,id_kdt,id_mape,id_num_valid_points,ood_0
0,I.10.7_1_0,lsrtransform,-c*sqrt(1 - m_0**2/m**2),-c * sqrt(1 - (m_0 / m) ** 2),50038,12509,575.986043,True,y_pred is close to y_true within tolerances; L...,NaN,1.186180e-12,2.868966e-13,1.000000,1.00000,1.000000,1.653165e-06,12509,None
1,I.11.19_0_0,lsrtransform,(A + x2*y2 + x3*y3)/y1,(A + x2 * y2 + x3 * y3) / y1,80000,20000,609.346425,True,y_pred is close to y_true within tolerances; L...,NaN,9.653734e-13,6.486476e-15,1.000000,1.00000,1.000000,3.337723e-08,20000,None
2,I.11.19_1_0,lsrtransform,(-A + x1*y1 - x3*y3)/y2,(x1 * y1 - x3 * y3 - A) / y2,80000,20000,419.131419,True,y_pred is close to y_true within tolerances; L...,NaN,5.720535e-13,6.180699e-15,1.000000,1.00000,1.000000,1.046009e-07,20000,None
3,I.11.19_2_0,lsrtransform,(-A + x1*y1 - x2*y2)/y3,(x1 * y1 - x2 * y2 - A) / y3,80000,20000,295.279508,True,y_pred is close to y_true within tolerances; L...,NaN,5.714315e-13,6.224127e-15,1.000000,1.00000,1.000000,5.600253e-08,20000,None
4,I.11.19_3_0,lsrtransform,(A + x2*y2 + x3*y3)/x1,(A + x2 * y2 + x3 * y3) / x1,80000,20000,381.354573,True,y_pred is close to y_true within tolerances; L...,NaN,9.934709e-13,6.551420e-15,1.000000,1.00000,1.000000,3.364354e-08,20000,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,III.21.20_2_0,lsrtransform,-j*m/(q*rho_c_0),-1 * m * j / (rho_c_0 * q),80000,20000,477.262459,True,y_pred is close to y_true within tolerances; L...,NaN,3.522013e-12,6.233403e-15,1.000000,1.00000,1.000000,4.629259e-08,20000,None
95,III.21.20_3_0,lsrtransform,-A_vec*q*rho_c_0/j,-rho_c_0 * q * A_vec / j + 1e-09 / j,80000,20000,414.002358,True,y_pred is close to y_true within tolerances; L...,NaN,9.145990e-14,3.977235e-15,1.000000,1.00000,1.000000,4.668273e-08,20000,None
96,III.4.33_3_0,lsrtransform,h*omega/(2*pi*kb*log(1 + h*omega/(2*pi*E_n))),((h * omega * (h * 0.0012020984 / E_n * log(om...,80000,20000,553.156073,False,y_pred is not close to y_true within tolerance...,NaN,7.343666e-05,4.791042e-06,0.999995,0.99835,0.999699,8.070141e-04,20000,None
97,III.9.52_0_0,lsrtransform,h*prob*t*(omega - omega_0)**2/(4*pi*Ef*(1 - co...,-1255154.5671792359 * 1 + 226561.3850197006 * ...,80000,20000,532.894573,False,y_pred is not close to y_true within tolerance...,NaN,1.929983e+13,1.010160e+00,-0.010160,0.00010,0.263906,1.946790e+05,20000,None
98,III.9.52_1_0,NaN,h*prob*t*(omega - omega_0)**2/(4*pi*p_d*(1 - c...,NaN,80000,20000,NaN,False,NaN,"compile() arg 1 must be a string, bytes or AST...",NaN,NaN,NaN,NaN,NaN,NaN,0,None

,start_time,problem_name,duration_seconds,best_formula,best_mse,status,progress,token_usage,money_usage,tools_usage,llm_model,best_rmse,best_mae,best_r2,best_node_id,times_usage,dirname,error
0,2026-05-27 10:48:28,I.10.7_1_0,576.356080,-c * sqrt(1 - (m_0 / m) ** 2),2.329631e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),279659,0.024273,"{'statistics_analysis': 8, 'evaluate_formula':...",deepseek/deepseek-v4-flash @ openrouter,4.826626e-07,2.554448e-07,1.000000,cd78202b5339404b839f695ecf4c3400:R1-C1-L2-K1,{'build_initial_prompt': 0.0005481243133544922...,I.10.7_1_0_20260527_104828,NaN
1,2026-05-27 09:09:01,I.11.19_0_0,610.260162,(A + x2 * y2 + x3 * y3) / y1,9.653122e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),341084,0.026003,"{'statistics_analysis': 10, 'code_executor': 2...",deepseek/deepseek-v4-flash @ openrouter,9.825030e-07,6.813457e-07,1.000000,d818f38b6f884b8981c661be088f7130:R1-C2-L5-K2,{'build_initial_prompt': 0.0010747909545898438...,I.11.19_0_0_20260527_090901,NaN
2,2026-05-27 12:13:27,I.11.19_1_0,419.553688,(x1 * y1 - x3 * y3 - A) / y2,5.727892e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),326341,0.023968,"{'statistics_analysis': 10, 'evaluate_formula'...",deepseek/deepseek-v4-flash @ openrouter,7.568284e-07,5.118843e-07,1.000000,9a7a4763e67b4948af94164cff10fa8c:R2-C2-L5-K1,{'build_initial_prompt': 0.0004868507385253906...,I.11.19_1_0_20260527_121327,NaN
3,2026-05-27 04:55:38,I.11.19_2_0,295.615137,(x1 * y1 - x2 * y2 - A) / y3,5.761264e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),330016,0.035153,"{'statistics_analysis': 9, 'evaluate_formula':...",deepseek/deepseek-v4-flash @ openrouter,7.590299e-07,5.146607e-07,1.000000,df28c409d005442d9526865929ae4a89:R1-C1-L5-K1,{'build_initial_prompt': 0.0005259513854980469...,I.11.19_2_0_20260527_045538,NaN
4,2026-05-27 11:26:45,I.11.19_3_0,381.512654,(A + x2 * y2 + x3 * y3) / x1,9.802123e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),347522,0.026115,"{'statistics_analysis': 18, 'predict_property'...",deepseek/deepseek-v4-flash @ openrouter,9.900567e-07,6.868412e-07,1.000000,70677d7ed98b46efa3375ea7e7c6df80:R1-C1-L5-K1,{'build_initial_prompt': 0.0005488395690917969...,I.11.19_3_0_20260527_112645,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,2026-05-27 10:21:06,III.21.20_2_0,477.272560,-1 * m * j / (rho_c_0 * q),3.706815e-12,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),271871,0.023094,"{'statistics_analysis': 9, 'predict_property':...",deepseek/deepseek-v4-flash @ openrouter,1.925309e-06,1.002608e-06,1.000000,f7b1afeeb2f0437d8c80cb872db7e3fa:R1-C1-L3-K1,{'build_initial_prompt': 0.0003895759582519531...,III.21.20_2_0_20260527_102106,NaN
95,2026-05-27 11:38:26,III.21.20_3_0,414.319234,-rho_c_0 * q * A_vec / j + 1e-09 / j,1.094230e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),343218,0.023820,"{'statistics_analysis': 10, 'code_executor': 1...",deepseek/deepseek-v4-flash @ openrouter,3.307915e-07,7.639981e-08,1.000000,5c675e8da65948a4a2985c2efb78dab3:R2-C1-L4-K2,{'build_initial_prompt': 0.0004589557647705078...,III.21.20_3_0_20260527_113826,NaN
96,2026-05-27 12:04:01,III.4.33_3_0,553.845787,((h * omega * (h * 0.0012020984 / E_n * log(om...,6.869194e-05,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),365387,0.030115,"{'statistics_analysis': 12, 'predict_property'...",deepseek/deepseek-v4-flash @ openrouter,8.288060e-03,9.106531e-04,0.999996,4f1c4e515f014b099baed4b48d99d2ca:R1-C1-L4-K2,{'build_initial_prompt': 0.0005502700805664062...,III.4.33_3_0_20260527_120401,NaN
97,2026-05-27 01:47:16,III.9.52_0_0,533.607458,-1255154.5671792359 * 1 + 226561.3850197006 * ...,4.782640e+14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),473929,0.052789,"{'statistics_analysis': 7, 'predict_property':...",deepseek/deepseek-v4-flash @ openrouter,2.186925e+07,4.347542e+05,0.000474,57d7b4eaafb54baabc6adfd618951a2c:R1-C1-L4-K2,{'build_initial_prompt': 0.0005617141723632812...,III.9.52_0_0_20260527_014716,NaN
98,2026-05-27 12:39:14,III.9.52_1_0,111.939335,NaN,NaN,failed,(R=1/2) × (C=1/2) × (L=5/5) × (K=2),59932,0.006259,"{'statistics_analysis': 2, 'code_executor': 5,...",deepseek/deepseek-v4-flash @ openrouter,NaN,NaN,NaN,NaN,{'build_initial_prompt': 0.0003764629364013672...,III.9.52_1_0_20260527_123914,"NameError(""name 'log_exception' is not defined"")"

,progress,name,params,ok,result,result_str,meta_data,dirname
0,(R=1/2) × (C=1/2) × (L=1/5) × (K=2),statistics_analysis,"{'variables': ['m', 'm_0', 'c', 'v']}",True,"{'statistics': {'m': {'n_samples': 50038, 'min...","Variable 'm': n=50038, min=1.0350, max=6.3547,...","{'timestamp': 1779850122.7749379, 'execution_t...",I.10.7_1_0_20260527_104828
1,(R=1/2) × (C=1/2) × (L=1/5) × (K=2),statistics_analysis,"{'variables': ['m', 'm_0', 'c', 'v']}",True,"{'statistics': {'m': {'n_samples': 50038, 'min...","Variable 'm': n=50038, min=1.0350, max=6.3547,...","{'timestamp': 1779850122.7840288, 'execution_t...",I.10.7_1_0_20260527_104828
2,(R=1/2) × (C=1/2) × (L=2/5) × (K=2),evaluate_formula,{'f': '-c * sqrt(1 - (m_0/m)**2)'},True,"{'formula': '-c * sqrt(1 - (m_0 / m) ** 2)', '...","{'formula': '-c * sqrt(1 - (m_0 / m) ** 2)', '...","{'timestamp': 1779850141.5088358, 'execution_t...",I.10.7_1_0_20260527_104828
3,(R=1/2) × (C=1/2) × (L=2/5) × (K=2),evaluate_formula,{'f': '-c * sqrt(1 - (m_0/m)**2)'},True,"{'formula': '-c * sqrt(1 - (m_0 / m) ** 2)', '...","{'formula': '-c * sqrt(1 - (m_0 / m) ** 2)', '...","{'timestamp': 1779850141.518665, 'execution_ti...",I.10.7_1_0_20260527_104828
4,(R=1/2) × (C=1/2) × (L=3/5) × (K=2),submit_formula,{'f': '-c * sqrt(1 - (m_0/m)**2)'},True,"{'formula': '-c * sqrt(1 - (m_0 / m) ** 2)', '...","{'formula': '-c * sqrt(1 - (m_0 / m) ** 2)', '...","{'timestamp': 1779850162.3844068, 'execution_t...",I.10.7_1_0_20260527_104828
...,...,...,...,...,...,...,...,...
5494,(R=1/2) × (C=1/2) × (L=2/5) × (K=2),predict_property,{},True,{'periodicity': {'prob': {'prediction': 'non-p...,Property Prediction Results (analyzed 5 variab...,"{'timestamp': 1779856784.7285285, 'execution_t...",III.9.52_1_0_20260527_123914
5495,(R=1/2) × (C=1/2) × (L=3/5) × (K=2),code_executor,"{'program': 'import sys, json import math data...",True,"{'success': False, 'output': '', 'error': 'Val...","{'success': False, 'output': '', 'error': 'Val...","{'timestamp': 1779856818.3998244, 'execution_t...",III.9.52_1_0_20260527_123914
5496,(R=1/2) × (C=1/2) × (L=3/5) × (K=2),code_executor,"{'program': 'import sys, json, math data_dict ...",True,"{'success': True, 'output': 'Omega_R (p_d*Ef/h...","{'success': True, 'output': ""Omega_R (p_d*Ef/h...","{'timestamp': 1779856818.7706125, 'execution_t...",III.9.52_1_0_20260527_123914
5497,(R=1/2) × (C=1/2) × (L=4/5) × (K=2),code_executor,"{'program': 'import sys, json, math, random da...",True,"{'success': True, 'output': 'sqrt(prob) * h / ...","{'success': True, 'output': 'sqrt(prob) * h / ...","{'timestamp': 1779856851.1863399, 'execution_t...",III.9.52_1_0_20260527_123914
5498,(R=1/2) × (C=1/2) × (L=4/5) × (K=2),code_executor,"{'program': 'import sys, json, math data_dict ...",True,"{'success': True, 'output': 'Checking relation...","{'success': True, 'output': 'Checking relation...","{'timestamp': 1779856851.5530846, 'execution_t...",III.9.52_1_0_20260527_123914

logs\bench_sr_agent\bench_my_sr_agent-v4-flash

status
completed    98
failed        1
Name: count, dtype: int64

       token_usage  money_usage
mean  3.398573e+05     0.029773
sum   3.364588e+07     2.947541

       symbolic_acc
mean       0.646465
count     99.000000
sum       64.000000

,equation_id,dataset_identifier,gt_expression,discovered_expression,num_train,num_test,search_time,symbolic_acc,symbolic_acc_detail,id_mse,id_nmse,id_r2,id_acc01,id_kdt,id_mape,id_num_valid_points,ood_0
0,I.11.19_2_0,lsrtransform,(-A + x1*y1 - x2*y2)/y3,(x1 * y1 - x2 * y2 - A) / y3,80000,20000,921.319035,True,y_pred is close to y_true within tolerances; L...,5.714315e-13,6.224127e-15,1.000000,1.000000,1.000000,5.600253e-08,20000,None
1,I.12.2_3_0,lsrtransform,-sqrt(q1*q2/(F*epsilon))/(2*sqrt(pi)),-sqrt(q1 * q2 / (12.566370614359172 * epsilon ...,80000,20000,837.518394,True,y_pred is close to y_true within tolerances; L...,2.854991e-15,2.513633e-15,1.000000,1.000000,1.000000,2.939437e-08,20000,None
2,I.12.4_2_0,lsrtransform,-sqrt(q1/(Ef*epsilon))/(2*sqrt(pi)),-sqrt(q1 / 12.566370614359172) / sqrt(epsilon ...,80000,20000,720.458005,True,y_pred is close to y_true within tolerances; L...,2.278641e-15,2.624916e-15,1.000000,1.000000,1.000000,2.713679e-08,20000,None
3,I.24.6_1_1,lsrtransform,sqrt(4*E_n/m - omega_0**2*x**2)/x,sqrt(4.00000000034527 * E_n / (m * x ** 2) - 1...,72373,18093,888.394924,True,y_pred is close to y_true within tolerances; L...,7.714239e-14,1.054881e-14,1.000000,1.000000,1.000000,7.645482e-08,18093,None
4,I.24.6_2_1,lsrtransform,sqrt(4*E_n/m - omega**2*x**2)/x,sqrt(4 * E_n / (m * x ** 2) - omega ** 2),72373,18093,1067.211387,True,y_pred is close to y_true within tolerances; L...,7.712604e-14,1.054657e-14,1.000000,1.000000,1.000000,7.642992e-08,18093,None
5,I.24.6_3_1,lsrtransform,2*sqrt(E_n/(m*(omega**2 + omega_0**2))),sqrt(4 * E_n / (m * omega_0 ** 2)) / sqrt(1 + ...,80000,20000,1151.081517,True,y_pred is close to y_true within tolerances; L...,1.874107e-14,8.012486e-15,1.000000,1.000000,1.000000,2.982162e-08,20000,None
6,I.29.16_0_0,lsrtransform,x2*cos(theta1 - theta2) - sqrt(x**2 + x2**2*co...,x2 * cos(theta1 - theta2) - sqrt(x ** 2 - x2 *...,64888,16221,1298.473868,True,y_pred is close to y_true within tolerances; L...,1.684544e-13,1.501687e-14,1.000000,1.000000,1.000000,1.598451e-07,16221,None
7,I.32.17_2_0,lsrtransform,sqrt(3)*sqrt(Pwr/(c*epsilon))*(-omega**2 + ome...,sqrt(Pwr) * (omega_0 ** 2 - omega ** 2) * sqrt...,80000,20000,1898.110566,True,y_pred is close to y_true within tolerances; L...,1.482794e-12,2.496152e-14,1.000000,1.000000,1.000000,7.525743e-08,20000,None
8,I.32.17_4_3,lsrtransform,sqrt(2*sqrt(3)*sqrt(pi)*Ef*omega_0**2*r*sqrt(P...,omega_0 / sqrt(1 + sqrt(4.1887902047863905 * e...,80000,20000,1230.138770,True,y_pred is close to y_true within tolerances; L...,1.057137e-14,3.230828e-14,1.000000,1.000000,1.000000,3.068499e-08,20000,None
9,I.32.5_0_1,lsrtransform,sqrt(6)*sqrt(pi)*sqrt(Pwr*c**3*epsilon)/a,sqrt(18.84955592153876 * Pwr * c * c * c * eps...,80000,20000,1207.871323,True,y_pred is close to y_true within tolerances; L...,6.113442e-12,6.835808e-15,1.000000,1.000000,1.000000,4.537923e-08,20000,None
10,I.32.5_1_1,lsrtransform,sqrt(6)*sqrt(pi)*sqrt(Pwr*c**3*epsilon)/q,sqrt(18.84955592153876) * sqrt(Pwr) * sqrt(eps...,80000,20000,986.707501,True,y_pred is close to y_true within tolerances; L...,6.113442e-12,6.835808e-15,1.000000,1.000000,1.000000,4.537923e-08,20000,None
11,I.37.4_1_1,lsrtransform,2*I1*cos(delta)**2 + I1 - Int + 2*sqrt(I1*(I1*...,-5013300115184.499 * 1 + 5697722897460.159 * s...,25006,6251,1645.112034,False,y_pred is not close to y_true within tolerance...,1.033820e-02,4.345836e-03,0.995654,0.495121,0.896236,8.803234e+02,6251,None
12,I.43.43_0_0,lsrtransform,1 + kb*v/(A*kappa),1 + kb * v / A / kappa,80000,20000,1087.286474,True,y_pred is close to y_true within tolerances; L...,7.273394e-14,3.622745e-15,1.000000,1.000000,1.000000,2.804356e-08,20000,None
13,I.43.43_3_0,lsrtransform,A*kappa*(gamma - 1)/kb,kappa * A * (gamma - 1) / kb,80000,20000,694.479437,True,y_pred is close to y_true within tolerances; L...,3.301334e-12,7.361114e-15,1.000000,1.000000,1.000000,5.228397e-08,20000,None
14,I.48.2_1_0,lsrtransform,-c*sqrt(1 - c**4*m**2/E_n**2),-c * sqrt(0.9999999515158282 - (m * c ** 2 / E...,59071,14767,740.110091,True,nsimplified f_pred to obtain y_pred. y_pred is...,6.168567e-13,2.327347e-13,1.000000,1.000000,1.000000,2.124356e-07,14767,None
15,II.11.27_0_0,lsrtransform,3*Pol/(alpha*(3*Ef*epsilon + Pol)),Pol / (alpha * (1.0000000369660997 * epsilon *...,80000,20000,1357.981821,True,y_pred is close to y_true within tolerances; L...,1.434277e-11,3.488687e-16,1.000000,1.000000,1.000000,4.094232e-08,20000,None
16,II.11.28_0_0,lsrtransform,3*(theta - 1)/(alpha*(theta - 4)),2.999999705696014 * (0.9999999773810906 - thet...,80000,20000,1209.233533,True,nsimplified f_pred to obtain y_pred. y_pred is...,3.730148e-10,3.547407e-15,1.000000,1.000000,1.000000,3.073607e-07,20000,None
17,II.11.3_3_1,lsrtransform,sqrt(Ef*q/(m*x) + omega**2),sqrt((q * Ef + m * x * omega ** 2) / (m * x)),80000,20000,783.313177,True,y_pred is close to y_true within tolerances; L...,1.272219e-14,6.204889e-15,1.000000,1.000000,1.000000,2.665010e-08,20000,None
18,II.11.3_4_1,lsrtransform,sqrt(-Ef*q/(m*x) + omega_0**2),omega_0 * sqrt(1 - q * Ef / (m * omega_0 ** 2 ...,70108,17527,849.767272,True,y_pred is close to y_true within tolerances; L...,5.365952e-14,7.175020e-14,1.000000,1.000000,1.000000,7.145734e-08,17527,None
19,II.13.23_1_0,lsrtransform,-c*sqrt(1 - rho_c_0**2/rho_c**2),-c * sqrt(1.0000000325118772 - (rho_c_0 / rho_...,47719,11929,967.304317,True,nsimplified f_pred to obtain y_pred. y_pred is...,5.005203e-13,1.201171e-13,1.000000,1.000000,1.000000,2.274235e-07,11929,None
20,II.13.34_1_0,lsrtransform,-c*j*sqrt(1/(c**2*rho_c_0**2 + j**2)),-j * c / sqrt(rho_c_0 ** 2 * c ** 2 + j ** 2),80000,20000,1281.626401,True,y_pred is close to y_true within tolerances; L...,8.596240e-15,5.792621e-15,1.000000,1.000000,1.000000,3.268178e-08,20000,None
21,II.15.4_1_0,lsrtransform,-E_n/(mom*cos(theta)),-0.2576613708140877 * E_n / cos(theta) + 0.700...,80000,20000,1097.864819,False,y_pred is not close to y_true within tolerance...,1.511433e+06,2.430934e-01,0.756907,0.143200,0.884325,9.351093e-01,20000,None
22,II.15.5_0_0,lsrtransform,-E_n/(Ef*cos(theta)),-(E_n + -0.002811570619199769) / (Ef * cos(the...,80000,20000,1292.268138,True,y_pred is not close to y_true within tolerance...,2.220885e+02,4.379472e-05,0.999956,0.998100,0.999880,2.359599e-03,20000,None
23,II.21.32_2_0,lsrtransform,c*q/(4*pi*Volt*epsilon*(c - v)),q * c / (12.566370614359172 * epsilon * Volt *...,80000,20000,935.421166,True,y_pred is close to y_true within tolerances; L...,3.838313e-14,3.656731e-15,1.000000,1.000000,1.000000,4.264805e-08,20000,None
24,II.24.17_0_1,lsrtransform,c*sqrt(d**2*k**2 + pi**2)/d,c * sqrt(k ** 2 + (3.1415926524018056 / d) ** 2),80000,20000,688.677258,True,y_pred is close to y_true within tolerances; L...,6.926963e-14,1.537019e-14,1.000000,1.000000,1.000000,3.424694e-08,20000,None
25,II.24.17_1_1,lsrtransform,d*omega*sqrt(1/(d**2*k**2 + pi**2)),omega * (k ** 2 + (3.141592653589793 / d) ** 2...,80000,20000,1015.075631,True,y_pred is close to y_true within tolerances; L...,4.289060e-15,1.658428e-14,1.000000,1.000000,1.000000,3.606552e-08,20000,None
26,II.24.17_2_1,lsrtransform,pi*c*sqrt(-1/((c*k - omega)*(c*k + omega))),2.2668220223133453 / ((omega / c) ** 2 - k ** ...,35030,8757,1366.571501,False,y_pred is not close to y_true within tolerance...,4.020028e-01,9.631439e-02,0.903686,0.010506,1.000000,3.790644e-01,8757,None
27,II.27.18_1_0,lsrtransform,-sqrt(E_den/epsilon),-exp(0.5 * log(E_den / epsilon)),80000,20000,645.739279,True,y_pred is close to y_true within tolerances; L...,2.333688e-14,6.442671e-15,1.000000,1.000000,1.000000,2.573440e-08,20000,None
28,II.34.29a_2_0,lsrtransform,h*q/(4*pi*mom),8.035581469808355e-10 * 1 + 0.0795774714739577...,80000,20000,1343.529466,True,y_pred is close to y_true within tolerances; L...,3.894166e-14,2.942555e-15,1.000000,1.000000,1.000000,4.137132e-08,20000,None
29,II.34.2_1_0,lsrtransform,2*mom/(q*r),2 * mom / (q * r),80000,20000,881.992532,True,y_pred is close to y_true within tolerances; L...,4.723435e-13,5.088090e-15,1.000000,1.000000,1.000000,4.131199e-08,20000,None
30,II.35.18_0_0,lsrtransform,n*exp(B*mom/(T*kb)) + n*exp(-B*mom/(T*kb)),0.9999999054931993 * n * exp(mom * B / (kb * T...,80000,20000,1108.255555,True,y_pred is close to y_true within tolerances; L...,7.173451e-11,1.674195e-13,1.000000,1.000000,1.000000,7.742054e-08,20000,None
31,II.35.21_2_1,lsrtransform,T*kb*log(sqrt(-(M + mom*n_rho)/(M - mom*n_rho)...,kb * T / (2.000000664413679 * mom) * (log(n_rh...,30585,7646,1214.004881,True,y_pred is close to y_true within tolerances; L...,1.550184e-11,2.051206e-12,1.000000,1.000000,1.000000,3.507650e-07,7646,None
32,II.36.38_1_0,lsrtransform,M*alpha/(c**2*epsilon) + T*f*kb/mom,f * kb * T / mom + alpha * M / (epsilon * c ** 2),80000,20000,659.550790,True,y_pred is close to y_true within tolerances; L...,9.554352e-13,8.627374e-15,1.000000,1.000000,1.000000,4.424613e-08,20000,None
33,II.36.38_5_0,lsrtransform,M*alpha*mom/(c**2*(H*mom - T*f*kb)),-155.62711748724067 * 1 + 8.136319576993372 * ...,80000,20000,1161.010182,False,y_pred is not close to y_true within tolerance...,8.478157e+02,1.012192e+00,-0.012192,0.009550,0.009552,2.788333e+01,20000,None
34,II.36.38_7_0,lsrtransform,c**2*epsilon*(H*mom - T*f*kb)/(alpha*mom),epsilon * (H - f * T * kb / mom) * c ** 2 / alpha,80000,20000,1289.900077,True,y_pred is close to y_true within tolerances; L...,6.653679e-11,1.243544e-14,1.000000,1.000000,1.000000,1.753220e-07,20000,None
35,II.37.1_0_0,lsrtransform,E_n/(B*(chi + 1)),E_n / (B * (chi + 1)),80000,20000,399.285886,True,y_pred is close to y_true within tolerances; L...,2.180945e-13,4.978602e-15,1.000000,1.000000,1.000000,3.869276e-08,20000,None
36,II.37.1_2_0,lsrtransform,-1 + E_n/(B*mom),E_n / B / mom - 1,80000,20000,1658.951236,True,y_pred is close to y_true within tolerances; L...,5.863876e-13,4.922592e-15,1.000000,1.000000,1.000000,1.362888e-07,20000,None
37,II.6.15a_1_0,lsrtransform,4*pi*Ef*epsilon*r**5/(3*z*sqrt(x**2 + y**2)),-71.598 - 3.923 * Ef - 56.887 * epsilon - 14.7...,80000,20000,1154.182076,False,y_pred is not close to y_true within tolerance...,2.050230e+02,2.296677e-03,0.997703,0.577850,0.917953,3.026284e+00,20000,None
38,II.6.15a_2_0,lsrtransform,2**(3/5)*3**(1/5)*(p_d*z*sqrt(x**2 + y**2)/(Ef...,sqrt(sqrt((x + y) / (20.646881 / p_d) / epsilo...,80000,20000,1532.989564,False,y_pred is not close to y_true within tolerance...,3.064238e-04,3.706980e-03,0.996293,0.999750,0.985681,4.876452e-03,20000,None
39,II.6.15a_3_1,lsrtransform,sqrt(16*pi**2*Ef**2*epsilon**2*r**10/(p_d**2*z...,sqrt(r ** 2 - y ** 2 - z ** 2),77219,19304,1218.970054,False,y_pred has non-finite values where y_true is f...,1.225274e+06,1.991911e+00,-0.991911,0.000000,0.216956,9.932020e-01,2926,None
40,II.6.15a_5_0,lsrtransform,4*pi*Ef*epsilon*r**5/(3*p_d*sqrt(x**2 + y**2)),sqrt(((Ef * 4 * 3.141592653589793 * epsilon * ...,80000,20000,1460.307909,False,y_pred has non-finite values where y_true is f...,7.771455e+04,8.151982e-01,0.184802,0.007596,0.904728,1.729485e+00,19879,None
41,II.6.15b_1_0,lsrtransform,8*pi*Ef*epsilon*r**3/(3*sin(2*theta)),Ef * epsilon * r ** 3,80000,20000,592.349562,False,y_pred is not close to y_true within tolerance...,7.828632e+05,1.000123e+00,-0.000123,0.000000,-0.362059,1.041920e+00,20000,None
42,III.10.19_1_1,lsrtransform,sqrt(-By**2 - Bz**2 + E_n**2/mom**2),sqrt(E_n ** 2 / mom ** 2 - By ** 2 - Bz ** 2 +...,59013,14753,700.944964,True,y_pred is close to y_true within tolerances; L...,4.546805e-13,9.705787e-15,1.000000,1.000000,1.000000,1.082268e-07,14753,None
43,III.10.19_3_1,lsrtransform,sqrt(-Bx**2 - By**2 + E_n**2/mom**2),sqrt(E_n ** 2 / mom ** 2 - Bx ** 2 - By ** 2),59013,14753,803.953743,True,y_pred is close to y_true within tolerances; L...,4.546785e-13,9.705743e-15,1.000000,1.000000,1.000000,1.082264e-07,14753,None
44,III.12.43_0_0,lsrtransform,2*pi*L/h,6.283185307179586 * L / h,80000,20000,905.958127,True,y_pred is close to y_true within tolerances; L...,7.717472e-14,5.134919e-15,1.000000,1.000000,1.000000,3.561498e-08,20000,None
45,III.15.12_0_0,lsrtransform,-E_n/(2*cos(d*k) - 2),E_n * 1 / (3.9870504007590535 * sin(k * d / 2....,80000,20000,1198.341132,True,y_pred is not close to y_true within tolerance...,3.162378e+09,3.283510e-04,0.999672,1.000000,1.000000,3.248863e-03,20000,None
46,III.15.14_1_0,lsrtransform,h**2/(8*pi**2*d**2*m),h * h / (78.95683520871486 * m * d * d),80000,20000,1073.273522,True,y_pred is close to y_true within tolerances; L...,4.411036e-13,7.724250e-15,1.000000,1.000000,1.000000,6.638637e-08,20000,None
47,III.19.51_1_0,lsrtransform,-2**(3/4)*(-E_n*epsilon**2*h**2*n**2/m)**(1/4),-(-E_n) ** 0.25 * 1.681792830507429 * sqrt(eps...,80000,20000,901.372821,True,y_pred is close to y_true within tolerances; L...,2.562151e-13,7.400189e-15,1.000000,1.000000,1.000000,2.825396e-08,20000,None
48,III.9.52_0_0,lsrtransform,h*prob*t*(omega - omega_0)**2/(4*pi*Ef*(1 - co...,-1255154.5671792359 * 1 + 226561.3850197006 * ...,80000,20000,1582.820366,False,y_pred is not close to y_true within tolerance...,1.929983e+13,1.010160e+00,-0.010160,0.000100,0.263906,1.946790e+05,20000,None

,start_time,problem_name,duration_seconds,best_formula,best_mse,status,progress,token_usage,money_usage,tools_usage,llm_model,best_rmse,best_mae,best_r2,best_node_id,times_usage,dirname,error
0,2026-05-27 09:23:31,I.11.19_2_0,921.372153,(x1 * y1 - x2 * y2 - A) / y3,5.761264e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),320444,0.335209,"{'statistics_analysis': 5, 'evaluate_formula':...",deepseek/deepseek-v4-pro @ openrouter,7.590299e-07,5.146607e-07,1.000000,4c25094ace7e4c239e2d4559bcbe1b19:R1-C1-L5-K1,{'build_initial_prompt': 0.0006601810455322266...,I.11.19_2_0_20260527_092331,NaN
1,2026-05-27 12:53:40,I.12.2_3_0,838.301282,-sqrt(q1 * q2 / (12.566370614359172 * epsilon ...,2.885397e-15,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),296059,0.206356,"{'statistics_analysis': 6, 'code_executor': 10...",deepseek/deepseek-v4-pro @ openrouter,5.371589e-08,2.996388e-08,1.000000,d091d52e6f864502b4e3885593ae88d7:R1-C1-L3-K1,{'build_initial_prompt': 0.0004830360412597656...,I.12.2_3_0_20260527_125340,NaN
2,2026-05-27 05:43:56,I.12.4_2_0,721.257253,-sqrt(q1 / 12.566370614359172) / sqrt(epsilon ...,2.308429e-15,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),291654,0.315987,"{'statistics_analysis': 6, 'evaluate_formula':...",deepseek/deepseek-v4-pro @ openrouter,4.804611e-08,2.954049e-08,1.000000,9ee093173b674f1c9cbce1853184eff0:R2-C1-L4-K2,{'build_initial_prompt': 0.0004968643188476562...,I.12.4_2_0_20260527_054356,NaN
3,2026-05-27 03:52:46,I.24.6_1_1,889.320501,sqrt(4.00000000034527 * E_n / (m * x ** 2) - 1...,7.915848e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),409297,0.522146,"{'statistics_analysis': 6, 'code_executor': 19...",deepseek/deepseek-v4-pro @ openrouter,2.813512e-07,2.007629e-07,1.000000,8a4dee9e68fb483f8a897ed1ead105fa:R2-C2-L3-K2,{'build_initial_prompt': 0.0004487037658691406...,I.24.6_1_1_20260527_035246,NaN
4,2026-05-27 05:56:05,I.24.6_2_1,1067.672893,sqrt(4 * E_n / (m * x ** 2) - omega ** 2),7.915944e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),430021,0.625783,"{'read_skill': 3, 'statistics_analysis': 4, 'c...",deepseek/deepseek-v4-pro @ openrouter,2.813529e-07,2.007629e-07,1.000000,7259423818e645ac9c05266c38d6c3f6:R1-C1-L4-K1,{'build_initial_prompt': 0.0004537105560302734...,I.24.6_2_1_20260527_055605,NaN
5,2026-05-27 01:38:45,I.24.6_3_1,1151.656495,sqrt(4 * E_n / (m * omega_0 ** 2)) / sqrt(1 + ...,1.894280e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),573520,0.832317,"{'statistics_analysis': 6, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,1.376329e-07,1.015453e-07,1.000000,bc80ed4b52f8461896092db99551731c:R2-C2-L3-K1,{'build_initial_prompt': 0.0005915164947509766...,I.24.6_3_1_20260527_013845,NaN
6,2026-05-27 11:04:23,I.29.16_0_0,1299.348272,x2 * cos(theta1 - theta2) - sqrt(x ** 2 - x2 *...,4.121335e-13,failed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),398731,0.425372,"{'statistics_analysis': 4, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,6.419762e-07,2.725150e-07,1.000000,1809f19dcc8a459da0d64b51e5e2a5d4:R1-C2-L3-K1,{'build_initial_prompt': 0.0004765987396240234...,I.29.16_0_0_20260527_110423,"NameError(""name 'log_exception' is not defined"")"
7,2026-05-27 08:51:46,I.32.17_2_0,1898.951691,sqrt(Pwr) * (omega_0 ** 2 - omega ** 2) * sqrt...,1.502260e-12,failed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),405254,0.362446,"{'read_skill': 6, 'statistics_analysis': 3, 'c...",deepseek/deepseek-v4-pro @ openrouter,1.225667e-06,7.703041e-07,1.000000,cb730f26ae9a4c089199b9504fc22456:R2-C1-L3-K1,{'build_initial_prompt': 0.0005078315734863281...,I.32.17_2_0_20260527_085146,"NameError(""name 'log_exception' is not defined"")"
8,2026-05-27 08:16:15,I.32.17_4_3,1230.161486,omega_0 / sqrt(1 + sqrt(4.1887902047863905 * e...,1.070994e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),386131,0.330335,"{'statistics_analysis': 4, 'polynomial_fit': 1...",deepseek/deepseek-v4-pro @ openrouter,1.034888e-07,8.268017e-08,1.000000,46f549cddd5d41d79ae38c0a28731681:R1-C2-L5-K2,{'build_initial_prompt': 0.0004472732543945312...,I.32.17_4_3_20260527_081615,NaN
9,2026-05-27 02:15:01,I.32.5_0_1,1207.892048,sqrt(18.84955592153876 * Pwr * c * c * c * eps...,6.499411e-12,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),319182,0.368718,"{'statistics_analysis': 6, 'evaluate_formula':...",deepseek/deepseek-v4-pro @ openrouter,2.549394e-06,1.477502e-06,1.000000,e43d855c5a684986b27ee1793b90f411:R2-C1-L4-K1,{'build_initial_prompt': 0.0006549358367919922...,I.32.5_0_1_20260527_021501,NaN
10,2026-05-27 01:58:18,I.32.5_1_1,987.565030,sqrt(18.84955592153876) * sqrt(Pwr) * sqrt(eps...,6.499411e-12,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),350415,0.415713,"{'statistics_analysis': 6, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,2.549394e-06,1.477502e-06,1.000000,8c0c6704a96f481496adfa69c13109c9:R1-C1-L4-K1,{'build_initial_prompt': 0.0005133152008056641...,I.32.5_1_1_20260527_015818,NaN
11,2026-05-27 09:38:56,I.37.4_1_1,1644.921153,-5013300115184.499 * 1 + 5697722897460.159 * s...,9.479188e-03,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),442979,0.461851,"{'statistics_analysis': 4, 'code_executor': 28...",deepseek/deepseek-v4-pro @ openrouter,9.736112e-02,6.074121e-02,0.995829,93ca58e7e3ad4f329df526ae00810675:R2-C2-L5-K1,{'build_initial_prompt': 0.0003683567047119140...,I.37.4_1_1_20260527_093855,NaN
12,2026-05-27 03:34:35,I.43.43_0_0,1088.164409,1 + kb * v / A / kappa,8.122250e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),404697,0.527808,"{'statistics_analysis': 7, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,2.849956e-07,8.238806e-08,1.000000,90a5af03e2a7480f895240ce297af68f:R1-C2-L4-K1,{'build_initial_prompt': 0.0005328655242919922...,I.43.43_0_0_20260527_033435,NaN
13,2026-05-27 06:13:57,I.43.43_3_0,695.089437,kappa * A * (gamma - 1) / kb,3.523403e-12,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),387722,0.528716,"{'read_skill': 5, 'statistics_analysis': 8, 'p...",deepseek/deepseek-v4-pro @ openrouter,1.877073e-06,1.037078e-06,1.000000,aba7c0a4796e48e2afe0bac08d2d2613:R2-C1-L4-K1,"{'build_initial_prompt': 0.000522613525390625,...",I.43.43_3_0_20260527_061357,NaN
14,2026-05-26 23:45:41,I.48.2_1_0,740.880519,-c * sqrt(0.9999999515158282 - (m * c ** 2 / E...,8.587367e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),281787,0.312845,"{'statistics_analysis': 6, 'code_executor': 12...",deepseek/deepseek-v4-pro @ openrouter,9.266805e-07,2.897466e-07,1.000000,7e2709616e474ef7a34a19f449420997:R1-C1-L2-K2,{'build_initial_prompt': 0.0005884170532226562...,I.48.2_1_0_20260526_234541,NaN
15,2026-05-27 10:41:42,II.11.27_0_0,1358.280772,Pol / (alpha * (1.0000000369660997 * epsilon *...,4.894042e-11,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),429354,0.448829,"{'statistics_analysis': 4, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,6.995743e-06,3.151046e-07,1.000000,76d5eb6cd9344b708d0939e2125056c1:R2-C2-L5-K1,{'build_initial_prompt': 0.0004377365112304687...,II.11.27_0_0_20260527_104142,NaN
16,2026-05-27 12:18:50,II.11.28_0_0,1209.912242,2.999999705696014 * (0.9999999773810906 - thet...,8.068739e-10,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),392185,0.423684,"{'statistics_analysis': 7, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,2.840553e-05,1.053899e-06,1.000000,c14d5b05582c43c7b42b8926dce00e1a:R2-C1-L4-K2,{'build_initial_prompt': 0.0004017353057861328...,II.11.28_0_0_20260527_121850,NaN
17,2026-05-27 04:40:58,II.11.3_3_1,784.009938,sqrt((q * Ef + m * x * omega ** 2) / (m * x)),1.211290e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),336877,0.427092,"{'statistics_analysis': 8, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,1.100586e-07,7.982160e-08,1.000000,fd1c9c8a7b7d43c4b4bc40ddfd7391cc:R2-C1-L3-K1,{'build_initial_prompt': 0.0005307197570800781...,II.11.3_3_1_20260527_044058,NaN
18,2026-05-27 12:39:05,II.11.3_4_1,850.594222,omega_0 * sqrt(1 - q * Ef / (m * omega_0 ** 2 ...,5.414591e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),320692,0.231383,"{'statistics_analysis': 5, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,2.326927e-07,1.461820e-07,1.000000,2e2bd41db6f94aa0962a32d130b6a3cc:R2-C2-L4-K2,{'build_initial_prompt': 0.0006611347198486328...,II.11.3_4_1_20260527_123905,NaN
19,2026-05-27 01:22:35,II.13.23_1_0,967.567081,-c * sqrt(1.0000000325118772 - (rho_c_0 / rho_...,8.557780e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),377068,0.427034,"{'statistics_analysis': 9, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,9.250827e-07,3.030785e-07,1.000000,96c40d11463c4651961130c4de870cc1:R1-C1-L4-K2,{'build_initial_prompt': 0.0004508495330810547...,II.13.23_1_0_20260527_012235,NaN
20,2026-05-27 10:20:15,II.13.34_1_0,1281.728653,-j * c / sqrt(rho_c_0 ** 2 * c ** 2 + j ** 2),8.794313e-15,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),328093,0.269244,"{'statistics_analysis': 5, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,9.377800e-08,6.780235e-08,1.000000,a4abbf19fa9249d09338779ae1b41735:R1-C1-L3-K1,"{'build_initial_prompt': 0.000579833984375, 'i...",II.13.34_1_0_20260527_102015,NaN
21,2026-05-27 04:54:10,II.15.4_1_0,1098.739116,-0.2576613708140877 * E_n / cos(theta) + 0.700...,1.086139e+05,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),499506,0.655771,"{'read_skill': 4, 'statistics_analysis': 6, 'p...",deepseek/deepseek-v4-pro @ openrouter,3.295662e+02,1.585800e+01,0.825454,27a42850783c4924a116446d4c06372d:R2-C2-L5-K1,{'build_initial_prompt': 0.0004796981811523437...,II.15.4_1_0_20260527_045410,NaN
22,2026-05-26 23:24:02,II.15.5_0_0,1292.634314,-(E_n + -0.002811570619199769) / (Ef * cos(the...,1.219757e+00,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),436322,0.598338,"{'statistics_analysis': 7, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,1.104426e+00,1.679358e-02,0.999998,170531699acb4b02923020031bc5b77b:R2-C2-L3-K1,{'build_initial_prompt': 0.0003566741943359375...,II.15.5_0_0_20260526_232402,NaN
23,2026-05-27 07:36:43,II.21.32_2_0,936.261077,q * c / (12.566370614359172 * epsilon * Volt *...,4.009915e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),322117,0.324492,"{'statistics_analysis': 6, 'evaluate_formula':...",deepseek/deepseek-v4-pro @ openrouter,2.002477e-07,6.597273e-08,1.000000,ad4a5c122e5645268ac98d1292c7565a:R2-C1-L4-K2,{'build_initial_prompt': 0.0004875659942626953...,II.21.32_2_0_20260527_073643,NaN
24,2026-05-27 04:07:41,II.24.17_0_1,689.341706,c * sqrt(k ** 2 + (3.1415926524018056 / d) ** 2),6.918900e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),535371,0.545710,"{'statistics_analysis': 8, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,2.630380e-07,2.007207e-07,1.000000,50ccf5f00a754842bce11727c0857073:R2-C2-L1-K1,{'build_initial_prompt': 0.0004208087921142578...,II.24.17_0_1_20260527_040741,NaN
25,2026-05-27 11:26:06,II.24.17_1_1,1015.330769,omega * (k ** 2 + (3.141592653589793 / d) ** 2...,4.300139e-15,failed,(R=2/2) × (C=2/2) × (L=4/5) × (K=2),348134,0.242179,"{'statistics_analysis': 4, 'code_executor': 16...",deepseek/deepseek-v4-pro @ openrouter,6.557545e-08,5.055332e-08,1.000000,7f806b90696d4ce7b2c7c7c3dd8fa2b9:R2-C1-L4-K1,{'build_initial_prompt': 0.0003826618194580078...,II.24.17_1_1_20260527_112606,"NameError(""name 'log_exception' is not defined"")"
26,2026-05-27 07:52:27,II.24.17_2_1,1366.826037,2.2668220223133453 / ((omega / c) ** 2 - k ** ...,8.104789e-01,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),433907,0.411505,"{'statistics_analysis': 7, 'code_executor': 28...",deepseek/deepseek-v4-pro @ openrouter,9.002660e-01,5.701982e-01,0.998873,2117b3cb81c4467d8e47514da2ef232a:R2-C1-L4-K1,{'build_initial_prompt': 0.0005311965942382812...,II.24.17_2_1_20260527_075227,NaN
27,2026-05-27 03:16:58,II.27.18_1_0,645.851274,-exp(0.5 * log(E_den / epsilon)),2.352282e-14,failed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),261255,0.316527,"{'statistics_analysis': 6, 'code_executor': 12...",deepseek/deepseek-v4-pro @ openrouter,1.533715e-07,1.158821e-07,1.000000,cd89f1e32aa2473aaa1b69a19c5408a8:R2-C1-L4-K1,{'build_initial_prompt': 0.0008807182312011719...,II.27.18_1_0_20260527_031658,"NameError(""name 'log_exception' is not defined"")"
28,2026-05-27 07:14:08,II.34.29a_2_0,1344.158403,8.035581469808355e-10 * 1 + 0.0795774714739577...,4.337529e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),386056,0.311929,"{'statistics_analysis': 4, 'code_executor': 23...",deepseek/deepseek-v4-pro @ openrouter,2.082673e-07,7.493221e-08,1.000000,08cc80454e754455b6e5da536a4a916a:R2-C2-L5-K2,"{'build_initial_prompt': 0.0004730224609375, '...",II.34.29a_2_0_20260527_071408,NaN
29,2026-05-27 08:37:02,II.34.2_1_0,882.233965,2 * mom / (q * r),4.816866e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),324724,0.368019,"{'statistics_analysis': 8, 'code_executor': 15...",deepseek/deepseek-v4-pro @ openrouter,6.940364e-07,3.945153e-07,1.000000,a936ea7fa4474f72a8246dfee7a68a55:R1-C1-L3-K1,{'build_initial_prompt': 0.0005331039428710938...,II.34.2_1_0_20260527_083702,NaN
30,2026-05-27 00:18:36,II.35.18_0_0,1108.847158,0.9999999054931993 * n * exp(mom * B / (kb * T...,4.044720e-11,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),433673,0.576830,"{'statistics_analysis': 6, 'evaluate_formula':...",deepseek/deepseek-v4-pro @ openrouter,6.359812e-06,6.461365e-07,1.000000,28e9fd9431414f04b35fa1871751e05c:R2-C2-L5-K2,{'build_initial_prompt': 0.0004949569702148438...,II.35.18_0_0_20260527_001836,NaN
31,2026-05-26 23:58:11,II.35.21_2_1,1214.725739,kb * T / (2.000000664413679 * mom) * (log(n_rh...,1.150763e-09,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),507098,0.575573,"{'statistics_analysis': 4, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,3.392289e-05,1.293337e-06,1.000000,517592d920e448629d57bff53871abe8:R2-C1-L3-K1,{'build_initial_prompt': 0.0004572868347167969...,II.35.21_2_1_20260526_235811,NaN
32,2026-05-26 23:12:55,II.36.38_1_0,660.297729,f * kb * T / mom + alpha * M / (epsilon * c ** 2),9.416275e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),361009,0.457614,"{'statistics_analysis': 7, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,9.703749e-07,5.998337e-07,1.000000,b8fe5faab8c448bda3275457e584529c:R2-C2-L3-K2,{'build_initial_prompt': 0.0004627704620361328...,II.36.38_1_0_20260526_231255,NaN
33,2026-05-27 05:24:21,II.36.38_5_0,1160.552637,-155.62711748724067 * 1 + 8.136319576993372 * ...,4.528462e+03,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),576620,0.768439,"{'statistics_analysis': 7, 'code_executor': 27...",deepseek/deepseek-v4-pro @ openrouter,6.729385e+01,3.479622e+00,0.002456,ec0b955ce56246c9a0c97637355196a4:R1-C1-L3-K1,{'build_initial_prompt': 0.0004444122314453125...,II.36.38_5_0_20260527_052421,NaN
34,2026-05-27 04:19:15,II.36.38_7_0,1290.877322,epsilon * (H - f * T * kb / mom) * c ** 2 / alpha,6.295352e-11,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),519401,0.735406,"{'statistics_analysis': 6, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,7.934325e-06,3.812350e-06,1.000000,e906f487dae24ea7b0a9a4ec02ae466b:R2-C1-L5-K2,{'build_initial_prompt': 0.0004227161407470703...,II.36.38_7_0_20260527_041915,NaN
35,2026-05-27 03:27:51,II.37.1_0_0,399.484478,E_n / (B * (chi + 1)),2.185037e-13,failed,(R=2/2) × (C=1/2) × (L=5/5) × (K=2),204862,0.206023,"{'statistics_analysis': 6, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,4.674438e-07,2.849743e-07,1.000000,55674919f01c4f04b513b7d9861f8c8f:R1-C2-L4-K1,{'build_initial_prompt': 0.0004727840423583984...,II.37.1_0_0_20260527_032751,"NameError(""name 'log_exception' is not defined"")"
36,2026-05-27 06:46:21,II.37.1_2_0,1659.787589,E_n / B / mom - 1,6.073560e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),469412,0.493525,"{'statistics_analysis': 5, 'read_skill': 4, 'c...",deepseek/deepseek-v4-pro @ openrouter,7.793305e-07,4.408776e-07,1.000000,e27f99efe68f4b108063c4510145e8d9:R2-C2-L4-K1,"{'build_initial_prompt': 0.002219676971435547,...",II.37.1_2_0_20260527_064621,NaN
37,2026-05-26 22:48:10,II.6.15a_1_0,1154.065958,-71.598 - 3.923 * Ef - 56.887 * epsilon - 14.7...,2.221674e+02,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),421604,0.589119,"{'statistics_analysis': 5, 'read_skill': 3, 'c...",deepseek/deepseek-v4-pro @ openrouter,1.490528e+01,7.649500e+00,0.997560,eaf2015100124c20ad34f0793902121e:R2-C2-L4-K2,{'build_initial_prompt': 0.0005788803100585938...,II.6.15a_1_0_20260526_224810,NaN
38,2026-05-27 00:55:14,II.6.15a_2_0,1533.689637,sqrt(sqrt((x + y) / (20.646881 / p_d) / epsilo...,2.318946e-04,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),428579,0.564973,"{'statistics_analysis': 7, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,1.522809e-02,5.506730e-03,0.997001,254d929201554cb2a6aefed8deae84b0:R2-C1-L5-K1,{'build_initial_prompt': 0.0005481243133544922...,II.6.15a_2_0_20260527_005514,NaN
39,2026-05-27 11:43:09,II.6.15a_3_1,1219.008966,sqrt(r ** 2 - y ** 2 - z ** 2),NaN,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),399788,0.453230,"{'statistics_analysis': 7, 'evaluate_formula':...",deepseek/deepseek-v4-pro @ openrouter,NaN,NaN,NaN,225e7598c15544f7b270fbd1f0feede4:R1-C1-L2-K1,{'build_initial_prompt': 0.0004227161407470703...,II.6.15a_3_1_20260527_114309,NaN
40,2026-05-27 13:07:48,II.6.15a_5_0,1461.222443,sqrt(((Ef * 4 * 3.141592653589793 * epsilon * ...,NaN,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),423149,0.339008,"{'statistics_analysis': 7, 'code_executor': 29...",deepseek/deepseek-v4-pro @ openrouter,NaN,NaN,NaN,b0a8c7f3694546259b665024806275ea:R1-C2-L2-K1,{'build_initial_prompt': 0.0004265308380126953...,II.6.15a_5_0_20260527_130748,NaN
41,2026-05-26 22:38:12,II.6.15b_1_0,593.057677,Ef * epsilon * r ** 3,1.695189e+08,failed,(R=1/2) × (C=2/2) × (L=5/5) × (K=2),148192,0.249981,"{'statistics_analysis': 4, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,1.301994e+04,1.252849e+02,-0.000002,f6637c22e06642b99f6830c8bd9d3c8b:R1-C1-L2-K1,{'build_initial_prompt': 0.0002257823944091797...,II.6.15b_1_0_20260526_223812,JSONDecodeError('Unterminated string starting ...
42,2026-05-27 05:12:34,III.10.19_1_1,701.741054,sqrt(E_n ** 2 / mom ** 2 - By ** 2 - Bz ** 2 +...,5.399815e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),320960,0.455878,"{'statistics_analysis': 8, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,7.348343e-07,4.622951e-07,1.000000,8830f3c7ab1e41e39232796965936d5d:R2-C1-L5-K1,{'build_initial_prompt': 0.0005898475646972656...,III.10.19_1_1_20260527_051234,NaN
43,2026-05-27 10:06:44,III.10.19_3_1,804.871419,sqrt(E_n ** 2 / mom ** 2 - Bx ** 2 - By ** 2),5.399845e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),314035,0.267816,"{'statistics_analysis': 6, 'predict_property':...",deepseek/deepseek-v4-pro @ openrouter,7.348364e-07,4.622951e-07,1.000000,9355dc21c5914436884b58de7bc60e70:R1-C1-L2-K2,{'build_initial_prompt': 0.0003986358642578125...,III.10.19_3_1_20260527_100644,NaN
44,2026-05-27 12:03:42,III.12.43_0_0,906.271666,6.283185307179586 * L / h,7.677492e-14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),345187,0.244386,"{'statistics_analysis': 5, 'code_executor': 22...",deepseek/deepseek-v4-pro @ openrouter,2.770829e-07,1.783538e-07,1.000000,844e2d5313d14c9d91e4ecce3c6eebb9:R1-C1-L3-K1,{'build_initial_prompt': 0.0004534721374511719...,III.12.43_0_0_20260527_120342,NaN
45,2026-05-27 06:25:34,III.15.12_0_0,1199.135445,E_n * 1 / (3.9870504007590535 * sin(k * d / 2....,9.443695e+07,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),378954,0.524122,"{'statistics_analysis': 7, 'code_executor': 25...",deepseek/deepseek-v4-pro @ openrouter,9.717868e+03,8.780114e+01,0.999987,0b1250b228f34d61b659dbe64bc68baf:R2-C2-L2-K1,{'build_initial_prompt': 0.0006351470947265625...,III.15.12_0_0_20260527_062534,NaN

,progress,name,params,ok,result,result_str,meta_data,dirname
0,(R=1/2) × (C=1/2) × (L=1/5) × (K=2),statistics_analysis,"{'variables': ['A', 'x1', 'x2', 'y1', 'y2', 'y...",True,"{'statistics': {'A': {'n_samples': 80000, 'min...","Variable 'A': n=80000, min=8.4000, max=58.0224...","{'timestamp': 1779845022.066099, 'execution_ti...",I.11.19_2_0_20260527_092331
1,(R=1/2) × (C=1/2) × (L=1/5) × (K=2),statistics_analysis,"{'variables': ['A', 'x1', 'x2', 'y1', 'y2', 'y...",True,"{'statistics': {'A': {'n_samples': 80000, 'min...","Variable 'A': n=80000, min=8.4000, max=58.0224...","{'timestamp': 1779845022.0906675, 'execution_t...",I.11.19_2_0_20260527_092331
2,(R=1/2) × (C=1/2) × (L=2/5) × (K=2),evaluate_formula,"{'f': '(A - x1*y1 - x2*y2) / y3', 'y': 'x3', '...",True,"{'formula': '(A - x1 * y1 - x2 * y2) / y3', 'm...","{'formula': '(A - x1 * y1 - x2 * y2) / y3', 'm...","{'timestamp': 1779845047.6578424, 'execution_t...",I.11.19_2_0_20260527_092331
3,(R=1/2) × (C=1/2) × (L=2/5) × (K=2),evaluate_formula,"{'f': '(A - x1*y1 - x2*y2) / y3', 'fit': False}",True,"{'formula': '(A - x1 * y1 - x2 * y2) / y3', 'm...","{'formula': '(A - x1 * y1 - x2 * y2) / y3', 'm...","{'timestamp': 1779845047.6741235, 'execution_t...",I.11.19_2_0_20260527_092331
4,(R=1/2) × (C=1/2) × (L=3/5) × (K=2),code_executor,"{'program': 'import sys, json import numpy as ...",True,"{'success': True, 'output': 'Residual A - x1*y...","{'success': True, 'output': 'Residual A - x1*y...","{'timestamp': 1779845101.9491584, 'execution_t...",I.11.19_2_0_20260527_092331
...,...,...,...,...,...,...,...,...
3090,(R=2/2) × (C=2/2) × (L=4/5) × (K=2),code_executor,"{'program': ' import sys, json import numpy as...",True,"{'success': True, 'output': 'Testing Rabi form...","{'success': True, 'output': 'Testing Rabi form...","{'timestamp': 1779821876.5362766, 'execution_t...",III.9.52_0_0_20260527_023515
3091,(R=2/2) × (C=2/2) × (L=4/5) × (K=2),code_executor,"{'program': 'import sys, json import numpy as ...",True,"{'success': False, 'output': '', 'error': 'Nam...","{'success': False, 'output': '', 'error': ""Nam...","{'timestamp': 1779821876.8671553, 'execution_t...",III.9.52_0_0_20260527_023515
3092,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),code_executor,"{'program': 'import sys, json import numpy as ...",True,"{'success': True, 'output': 'Points with p_d >...","{'success': True, 'output': 'Points with p_d >...","{'timestamp': 1779822096.8530278, 'execution_t...",III.9.52_0_0_20260527_023515
3093,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),code_executor,"{'program': 'import sys, json import numpy as ...",True,"{'success': True, 'output': 'corr(p_d, h*prob/...","{'success': True, 'output': ""corr(p_d, h*prob/...","{'timestamp': 1779822097.2552996, 'execution_t...",III.9.52_0_0_20260527_023515
3094,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),code_executor,"{'program': ' import sys, json import numpy as...",True,"{'success': True, 'output': 'p_d > 1e6: 78 poi...","{'success': True, 'output': 'p_d > 1e6: 78 poi...","{'timestamp': 1779822097.6137593, 'execution_t...",III.9.52_0_0_20260527_023515

logs\bench_sr_agent\bench_my_sr_agent_deepseek-v4-pro

status
completed    43
failed        6
Name: count, dtype: int64

      token_usage  money_usage
mean     385929.0     0.444191
sum    18910521.0    21.765371

       symbolic_acc
mean       0.795918
count     49.000000
sum       39.000000

In [ ]:
# print(save_dir)
# display(df_details['status'].value_counts())
# display(df_details[['token_usage', 'money_usage']].agg(['mean', 'sum']))
# display(df_results['symbolic_acc'].agg(['mean', 'count', 'sum']).to_frame())

In [25]:
print(save_dir)
display(df_details['status'].value_counts())
display(df_details[['token_usage', 'money_usage']].agg(['mean', 'sum']))
display(df_results['symbolic_acc'].agg(['mean', 'count', 'sum']).to_frame())

logs\bench_sr_agent\bench_my_sr_agent-v4-flash

status
completed    62
Name: count, dtype: int64

       token_usage  money_usage
mean  3.468420e+05     0.031578
sum   2.150420e+07     1.957830

       symbolic_acc
mean       0.645161
count     62.000000
sum       40.000000

In [22]:
print(save_dir)
display(df_details['status'].value_counts())
display(df_details[['token_usage', 'money_usage']].agg(['mean', 'sum']))
display(df_results['symbolic_acc'].agg(['mean', 'count', 'sum']).to_frame())

logs\bench_sr_agent\bench_my_sr_agent_deepseek-v4-pro

status
completed    30
failed        3
Name: count, dtype: int64

       token_usage  money_usage
mean  3.950176e+05     0.495637
sum   1.303558e+07    16.356025

       symbolic_acc
mean       0.787879
count     33.000000
sum       26.000000

# Backup

In [ ]:
df_results[df_results['id_nmse'] < 1e-7].head(20)[['gt_expression', 'discovered_expression', 'id_mse', 'id_nmse', 'id_r2']].to_dict(orient='records')

[{'gt_expression': '-c*sqrt(1 - m_0**2/m**2)',
  'discovered_expression': '-c * sqrt(1 - (m_0 / m) ** 2)',
  'id_mse': 1.186179604838356e-12,
  'id_nmse': 2.868965920266257e-13,
  'id_r2': 0.9999999999997131},
 {'gt_expression': '(A + x2*y2 + x3*y3)/y1',
  'discovered_expression': 'A / y1 + x2 * y2 / y1 + x3 * y3 / y1',
  'id_mse': 9.653733565080772e-13,
  'id_nmse': 6.48647610799236e-15,
  'id_r2': 0.9999999999999936},
 {'gt_expression': '(-A + x1*y1 - x2*y2)/y3',
  'discovered_expression': 'x1 * y1 / y3 - (x2 * y2 + A) / y3',
  'id_mse': 5.714314873132767e-13,
  'id_nmse': 6.2241271577015845e-15,
  'id_r2': 0.9999999999999938},
 {'gt_expression': '(A + x2*y2 + x3*y3)/x1',
  'discovered_expression': '(A + x2 * y2 + x3 * y3) / x1',
  'id_mse': 9.934709168225883e-13,
  'id_nmse': 6.5514204941579835e-15,
  'id_r2': 0.9999999999999934},
 {'gt_expression': '(-A + x1*y1 - x3*y3)/x2',
  'discovered_expression': '(x1 * y1 - x3 * y3 - A) / x2',
  'id_mse': 5.679918148415428e-13,
  'id_nmse': 6.06727087639076e-15,
  'id_r2': 0.9999999999999939},
 {'gt_expression': '(-A + x1*y1 - x2*y2)/x3',
  'discovered_expression': '(x1 * y1 - A - x2 * y2) / x3',
  'id_mse': 5.809720552347479e-13,
  'id_nmse': 6.3262994221442655e-15,
  'id_r2': 0.9999999999999937},
 {'gt_expression': '-sqrt(q1*q2/(F*epsilon))/(2*sqrt(pi))',
  'discovered_expression': '-sqrt(q1 * q2 / (12.566370614359172 * epsilon * F))',
  'id_mse': 2.8549910431550674e-15,
  'id_nmse': 2.5136330366755035e-15,
  'id_r2': 0.9999999999999974},
 {'gt_expression': '-sqrt(q1/(Ef*epsilon))/(2*sqrt(pi))',
  'discovered_expression': '-sqrt(q1 / (12.566370614 * epsilon * Ef))',
  'id_mse': 2.27867294744235e-15,
  'id_nmse': 2.62495318878403e-15,
  'id_r2': 0.9999999999999973},
 {'gt_expression': '-c*p*sqrt(1/(c**2*m_0**2 + p**2))',
  'discovered_expression': '-1 / sqrt((m_0 / p) ** 2 + 1 / c ** 2)',
  'id_mse': 8.382128173587436e-15,
  'id_nmse': 5.6772493271833215e-15,
  'id_r2': 0.9999999999999943},
 {'gt_expression': 'sqrt(4*E_n/m - omega**2*x**2)/x',
  'discovered_expression': 'sqrt(E_n / m * 3.9999974 / x ** 1.9999981 - omega ** 2)',
  'id_mse': 5.780168591128743e-12,
  'id_nmse': 7.904069382790153e-13,
  'id_r2': 0.9999999999992096},
 {'gt_expression': 'd2/foc - d2/d1',
  'discovered_expression': 'd2 * (d1 - foc) / (foc * d1)',
  'id_mse': 4.01019230573258e-14,
  'id_nmse': 3.6601416178352545e-15,
  'id_r2': 0.9999999999999963},
 {'gt_expression': 'x2*cos(theta1 - theta2) - sqrt(x**2 + x2**2*cos(theta1 - theta2)**2 - x2**2)',
  'discovered_expression': 'x2 * cos(theta1 - theta2) - sqrt(abs(x ** 2 - x2 ** 2 * sin(theta1 - theta2) ** 2))',
  'id_mse': 1.6845435131815617e-13,
  'id_nmse': 1.501686643740824e-14,
  'id_r2': 0.999999999999985},
 {'gt_expression': 'x1*cos(theta1 - theta2) - sqrt(x**2 + x1**2*cos(theta1 - theta2)**2 - x1**2)',
  'discovered_expression': '(x1 ** 2 - x ** 2) / (x1 * cos(theta2 - theta1) + sqrt(x ** 2 - x1 ** 2 * sin(theta2 - theta1) ** 2))',
  'id_mse': 1.6845435124163323e-13,
  'id_nmse': 1.50168664305866e-14,
  'id_r2': 0.999999999999985},
 {'gt_expression': 'sqrt(3)*sqrt(Pwr/(c*epsilon))*(-omega**2 + omega_0**2)/(2*sqrt(pi)*Ef*omega**2)',
  'discovered_expression': 'sqrt(-39.373493745180106 * Pwr / (49.879432974818755 * -3.3065192522545863 * epsilon * c * Ef ** 2)) * abs(omega_0 ** 2 - omega ** 2) / omega ** 2',
  'id_mse': 1.4821226957205731e-12,
  'id_nmse': 2.4950217000221786e-14,
  'id_r2': 0.999999999999975},
 {'gt_expression': 'sqrt(6)*sqrt(pi)*sqrt(Pwr*c**3*epsilon)/a',
  'discovered_expression': 'sqrt(18.84955592153876 * epsilon * c ** 3 * Pwr) / a',
  'id_mse': 6.113441747415258e-12,
  'id_nmse': 6.835808210369742e-15,
  'id_r2': 0.9999999999999931},
 {'gt_expression': 'c*omega*sqrt(1 - v**2/c**2)/(c + v)',
  'discovered_expression': 'omega / sqrt(1 - (v / c) ** 2) - omega * v / c / sqrt(1 - (v / c) ** 2)',
  'id_mse': 3.341224503711402e-14,
  'id_nmse': 7.556102957771666e-15,
  'id_r2': 0.9999999999999925},
 {'gt_expression': 'omega*(c - v)/c',
  'discovered_expression': 'omega * (c - v) / c',
  'id_mse': 4.368002027284165e-14,
  'id_nmse': 7.423548995234065e-15,
  'id_r2': 0.9999999999999926},
 {'gt_expression': 'T*kb*log(n_0/n)/(m*x)',
  'discovered_expression': '1.0000000017925066 * kb * T / (m * x) * log(n_0 / n)',
  'id_mse': 2.438605598627472e-14,
  'id_nmse': 4.692690977700496e-15,
  'id_r2': 0.9999999999999953},
 {'gt_expression': '1 + kb*v/(A*kappa)',
  'discovered_expression': 'kb * v / (kappa * A) + 1',
  'id_mse': 7.273393864085201e-14,
  'id_nmse': 3.6227449264254954e-15,
  'id_r2': 0.9999999999999963},
 {'gt_expression': 'A*kappa*(gamma - 1)/kb',
  'discovered_expression': 'kappa / kb * (gamma - 1) * A',
  'id_mse': 3.3013335289656497e-12,
  'id_nmse': 7.361113848520866e-15,
  'id_r2': 0.9999999999999927}]

In [11]:
from bench_sr_agent import DATASET_SPLITS, load_problems, build_argparser

parser = build_argparser()
args, _ = parser.parse_known_args()

datasets = list(DATASET_SPLITS.keys())
problems = []
for dataset in datasets:
    problems.extend(load_problems(dataset, args.data_root))

In [14]:
problems[0]

Problem(dataset_identifier='lsrtransform', equation_idx='II.6.15b_1_0', symbols=['p_d', 'Ef', 'epsilon', 'theta', 'r'], symbol_descs=['the dipole moment', 'the electric field', 'the electric constant or permittivity of the medium', 'the angle between the dipole axis and the position vector', 'the distance from the dipole to the point where the electric field is being measured'], symbol_properties=['O', 'V', 'V', 'V', 'V'], expression='8*pi*Ef*epsilon*r**3/(3*sin(2*theta))', samples={'test': array([[-1.89978886e+01,  5.25637604e-02,  1.82653153e+00,
         2.89664268e+00,  2.23163176e+00],
       [-3.33039780e+01, -1.37035444e-01,  2.89017677e+00,
         1.25211060e+00,  1.81440020e+00],
       [-1.55860071e+01,  8.87142196e-02,  2.63639474e+00,
         2.06723142e+00,  1.88169527e+00],
       ...,
       [-7.01482487e+00,  1.20707955e-02,  2.59601259e+00,
         1.96577024e+00,  2.66748810e+00],
       [-2.04217935e+00, -3.72400843e-02,  1.98443580e+00,
         1.00902021e+00,  1.43809414e+00],
       [-1.63505459e+01, -6.81044385e-02,  1.16933548e+00,
         1.17541265e+00,  2.59239483e+00]], shape=(20000, 5)), 'train': array([[ 2.43452225e+01, -7.24347308e-02,  1.23010910e+00,
         2.66968441e+00,  2.97802305e+00],
       [ 2.33715572e+01,  8.99118707e-02,  2.21813297e+00,
         1.20959222e+00,  2.09908938e+00],
       [-1.18772745e+00,  2.82837935e-02,  1.26678193e+00,
         2.48928094e+00,  1.56289458e+00],
       ...,
       [ 6.85458755e+00, -7.04168305e-02,  1.16030550e+00,
         2.12546992e+00,  2.07751894e+00],
       [ 8.32945703e+03, -1.41441569e-01,  2.58052969e+00,
         1.57347536e+00,  2.44384480e+00],
       [-5.07489204e+01,  8.89461637e-02,  1.89850497e+00,
         2.87059665e+00,  2.64502048e+00]], shape=(80000, 5))}, desc=None)

In [30]:
import nd2py as nd
from tqdm import tqdm
from sr_agent.utils import symbolic_acc, setup_logging

setup_logging()


for idx, row in tqdm(df_results.iterrows(), total=len(df_results)):
    for problem in problems:
        if row['equation_id'] == problem.equation_idx:
            break
    else:
        raise ValueError(f"Problem with equation_id {row['equation_id']} not found in loaded problems.")
    
    f_true = nd.parse(row['gt_expression'])
    f_pred = nd.parse(row['discovered_expression'])
    data = {var: problem.samples['train'][:, idx] for idx, var in enumerate(problem.symbols)}
    result = symbolic_acc(f_true, f_pred, data)
    df_results.loc[idx, 'symbolic_acc'] = result['symbolic_acc']
    print(f"Problem ID: {row['equation_id']}, Symbolic Accuracy: {result['symbolic_acc']}, Reason: {result['reason']}")

AttributeError: 'OutStream' object has no attribute 'reconfigure'

In [29]:
f_true, f_pred

(-c * sqrt(1 - m_0 ** 2 / m ** 2), -c * sqrt(1 - (m_0 / m) ** 2))