In [23]:
import os
import sys
from pathlib import Path
if os.getcwd().endswith('analysis'):
    ROOT = Path('..').absolute()
else:
    ROOT = Path('.').absolute()
os.chdir(ROOT)
sys.path.append(str(ROOT))
print(os.getcwd())

/mnt/mergerfs/yuzihan/MergedWorkSpace/42-MySRAgent/SRAgent

In [36]:
import json
import pandas as pd
from sr_agent.utils import tag2ansi

# save_dir = Path('logs/bench_sr_agent/bench_my_sr_agent')

for save_dir in [
    Path('logs/bench_sr_agent/bench_my_sr_agent-v4-flash'),
    Path('logs/bench_sr_agent/bench_my_sr_agent_deepseek-v4-pro'),
    Path('logs/bench_sr_agent/bench_my_sr_agent-v4-flash_ban_pysr_sindy'),
    Path('logs/bench_sr_agent/bench_my_sr_agent-v4-flash_ban_predict_property'),
    Path('logs/bench_sr_agent/bench_my_sr_agent_gpt-4o-mini'),
    # Path('logs/bench_sr_agent/bench_sr_scientist-v4-flash'),
]:
    if True: # Load df_results
        df_list = []
        for exp_path in sorted((save_dir / "results").glob('*.jsonl'), key=lambda x: x.stem):
            lines = [json.loads(line) for line in exp_path.read_text(encoding="utf-8").splitlines() if line.strip()]
            successful_lines = [line for line in lines if 'error' not in line]
            result = successful_lines[-1] if successful_lines else lines[-1]
            df_list.append(result)
        df_results = pd.DataFrame(df_list)

        df_id = pd.DataFrame(df_results.pop('id_metrics').tolist(), index=df_results.index).add_prefix('id_')
        df_results = df_results.join(df_id)

        df_ood = pd.DataFrame(df_results.pop('ood_metrics').tolist(), index=df_results.index).add_prefix('ood_')
        df_results = df_results.join(df_ood)
        # display(df_results)

    if True: # Load df_details
        df_list = []
        for exp_path in sorted((save_dir / "experiments").glob('*/result.jsonl'), key=lambda x: x.stem):
            dirname = exp_path.parent.name
            detail = json.loads(exp_path.read_text(encoding="utf-8").strip())
            detail['dirname'] = dirname
            df_list.append(detail)
        df_details = pd.DataFrame(df_list)
        # df_details['token_usage'] = df_details['token_usage'].str.removesuffix('token').str.replace(' k', 'e3').map(float)
        # df_details['money_usage'] = df_details['money_usage'].str.removesuffix('$').str.replace(' m', 'e-3').str.replace(' μ', 'e-6').map(float)
        df_details['token_usage'] = df_details['token_usage']
        df_details['money_usage'] = df_details['money_usage']
        # display(df_details)

    if True: # Load df_tool_calls
        df_list = []
        for exp_path in sorted((save_dir / "experiments").glob('*/tool_calls.jsonl'), key=lambda x: x.stem):
            dirname = exp_path.parent.name
            tool_calls = [json.loads(line) for line in exp_path.read_text(encoding="utf-8").splitlines() if line.strip()]
            for call in tool_calls:
                call['dirname'] = dirname
            df_list.extend(tool_calls)
        df_tool_calls = pd.DataFrame(df_list)
        # display(df_tool_calls)
    
    if True: # Display
        print(tag2ansi( "=" * 20 + f" [red bold]{save_dir.name}[reset] " + "=" * 20 ))
        display(df_details['status'].value_counts().to_frame().T)
        display(df_details[['token_usage', 'money_usage']].agg(['mean', 'sum']))
        display(df_results['symbolic_acc'].agg(['mean', 'count', 'sum']).to_frame().T)
        display(pd.DataFrame(df_details['tools_usage'].to_list()).fillna(0.0).agg(['mean', 'sum']).T.sort_index())

==================== bench_my_sr_agent-v4-flash ====================

status  completed  failed
count         109       2

       token_usage  money_usage
mean  3.412649e+05     0.029512
sum   3.788040e+07     3.275843

                  mean  count   sum
symbolic_acc  0.657658  111.0  73.0

                          mean     sum
call_pysr             0.819820    91.0
call_sindy            2.396396   266.0
code_executor        16.783784  1863.0
evaluate_formula     17.576577  1951.0
polynomial_fit        1.909910   212.0
predict_property      3.414414   379.0
read_skill            0.360360    40.0
statistics_analysis  10.792793  1198.0
submit_formula        1.288288   143.0

==================== bench_my_sr_agent_deepseek-v4-pro ====================

status  completed  failed
count          97      14

       token_usage  money_usage
mean  3.866872e+05     0.375338
sum   4.292228e+07    41.662519

                  mean  count   sum
symbolic_acc  0.765766  111.0  85.0

                          mean     sum
call_pysr             1.117117   124.0
call_sindy            2.198198   244.0
code_executor        20.054054  2226.0
evaluate_formula     25.612613  2843.0
polynomial_fit        0.900901   100.0
predict_property      2.198198   244.0
read_skill            2.018018   224.0
statistics_analysis   5.666667   629.0
submit_formula        1.828829   203.0

==================== bench_my_sr_agent-v4-flash_ban_pysr_sindy ====================

status  completed  failed
count         106       5

       token_usage  money_usage
mean  3.169673e+05     0.029097
sum   3.518337e+07     3.229755

                  mean  count   sum
symbolic_acc  0.558559  111.0  62.0

                          mean     sum
code_executor        19.567568  2172.0
evaluate_formula     13.306306  1477.0
polynomial_fit        1.414414   157.0
predict_property      4.072072   452.0
read_skill            1.009009   112.0
statistics_analysis  10.585586  1175.0
submit_formula        1.189189   132.0

==================== bench_my_sr_agent-v4-flash_ban_predict_property ====================

status  completed  failed
count         106       5

       token_usage  money_usage
mean  3.114339e+05     0.027063
sum   3.456916e+07     3.003984

                  mean  count   sum
symbolic_acc  0.603604  111.0  67.0

                          mean     sum
call_pysr             0.441441    49.0
call_sindy            1.477477   164.0
code_executor        18.432432  2046.0
evaluate_formula     13.594595  1509.0
polynomial_fit        1.216216   135.0
read_skill            0.189189    21.0
statistics_analysis  12.207207  1355.0
submit_formula        1.270270   141.0

==================== bench_my_sr_agent_gpt-4o-mini ====================

status  completed
count          59

       token_usage  money_usage
mean  1.827076e+05     0.022343
sum   1.077975e+07     1.318224

                  mean  count   sum
symbolic_acc  0.288136   59.0  17.0

                         mean    sum
call_pysr            3.983051  235.0
call_sindy           3.932203  232.0
code_executor        0.152542    9.0
evaluate_formula     9.084746  536.0
polynomial_fit       5.576271  329.0
predict_property     0.915254   54.0
statistics_analysis  6.559322  387.0
submit_formula       2.983051  176.0

In [15]:
import json
import pandas as pd

df_list = []
for path in Path('logs/baseline/coding_agent/codex_gpt55/').glob('*/results.json'):
    result = json.loads(path.read_text(encoding="utf-8").strip())
    df_list.append(result)
df_results = pd.DataFrame(df_list)

display(df_results['symbolic_acc'].agg(['mean', 'count', 'sum']).to_frame().T)

                  mean  count   sum
symbolic_acc  0.972603   73.0  71.0

[bench_sr_scientist-v4-flash|bench_sr_agent|N|May28 02:50:04|9:21:15.438942] Result saved to logs/bench_sr_agent/bench_sr_scientist-v4-flash/results/lsrtransform_II.11.3_0_
[bench_sr_scientist-v4-flash|bench_sr_agent|N|May28 02:50:04|9:21:15.440226] 
        ==================================================
        Summary of lsrtransform (111 problems)
        --------------------------------------------------
          Avg R2   (In-Domain): 0.571040
          Avg MSE  (In-Domain): 5353418704090333687635247104.000000
          Avg NMSE (In-Domain): 0.428960
          Avg MAPE (In-Domain): 466.375802
          Avg KDT  (In-Domain): 0.778709
          Avg Acc@0.1 (In-Domain): 0.473299
          Avg Valid Points (In-Domain): 18947.2
        --------------------------------------------------
             r2>=0.5:    83/111 (74.8%)
             r2>=0.9:    53/111 (47.7%)
            r2>=0.99:    38/111 (34.2%)
           r2>=0.999:    35/111 (31.5%)
        --------------------------------------------------
          Avg Search Time: 290.09s
          Avg Symbolic Accurate Rate: 0.180180
        ==================================================

In [ ]:
[bench_pysr|bench_sr_agent|N|May26 19:16:36|4:48:25.273753] Result saved to logs/bench_sr_agent/bench_pysr/results/lsrtra
[bench_pysr|bench_sr_agent|N|May26 19:16:36|4:48:25.274876] 
        ==================================================
        Summary of lsrtransform (111 problems)
        --------------------------------------------------
          Avg R2   (In-Domain): -498715551.011685
          Avg MSE  (In-Domain): 187255264202285508996889683644827828224.000000
          Avg NMSE (In-Domain): 498715552.011685
          Avg MAPE (In-Domain): 33275780231407716.000000
          Avg KDT  (In-Domain): 0.902690
          Avg Acc@0.1 (In-Domain): 0.877842
          Avg Valid Points (In-Domain): 18947.2
        --------------------------------------------------
             r2>=0.5:    99/111 (89.2%)
             r2>=0.9:    98/111 (88.3%)
            r2>=0.99:    97/111 (87.4%)
           r2>=0.999:    84/111 (75.7%)
        --------------------------------------------------
          Avg Search Time: 134.07s
          Avg Symbolic Accurate Rate: 0.504505
        ==================================================

# Backup

In [ ]:
# print(save_dir)
# display(df_details['status'].value_counts())
# display(df_details[['token_usage', 'money_usage']].agg(['mean', 'sum']))
# display(df_results['symbolic_acc'].agg(['mean', 'count', 'sum']).to_frame())

In [25]:
print(save_dir)
display(df_details['status'].value_counts())
display(df_details[['token_usage', 'money_usage']].agg(['mean', 'sum']))
display(df_results['symbolic_acc'].agg(['mean', 'count', 'sum']).to_frame())

logs\bench_sr_agent\bench_my_sr_agent-v4-flash

status
completed    62
Name: count, dtype: int64

       token_usage  money_usage
mean  3.468420e+05     0.031578
sum   2.150420e+07     1.957830

       symbolic_acc
mean       0.645161
count     62.000000
sum       40.000000

In [22]:
print(save_dir)
display(df_details['status'].value_counts())
display(df_details[['token_usage', 'money_usage']].agg(['mean', 'sum']))
display(df_results['symbolic_acc'].agg(['mean', 'count', 'sum']).to_frame())

logs\bench_sr_agent\bench_my_sr_agent_deepseek-v4-pro

status
completed    30
failed        3
Name: count, dtype: int64

       token_usage  money_usage
mean  3.950176e+05     0.495637
sum   1.303558e+07    16.356025

       symbolic_acc
mean       0.787879
count     33.000000
sum       26.000000

In [ ]:
df_results[df_results['id_nmse'] < 1e-7].head(20)[['gt_expression', 'discovered_expression', 'id_mse', 'id_nmse', 'id_r2']].to_dict(orient='records')

[{'gt_expression': '-c*sqrt(1 - m_0**2/m**2)',
  'discovered_expression': '-c * sqrt(1 - (m_0 / m) ** 2)',
  'id_mse': 1.186179604838356e-12,
  'id_nmse': 2.868965920266257e-13,
  'id_r2': 0.9999999999997131},
 {'gt_expression': '(A + x2*y2 + x3*y3)/y1',
  'discovered_expression': 'A / y1 + x2 * y2 / y1 + x3 * y3 / y1',
  'id_mse': 9.653733565080772e-13,
  'id_nmse': 6.48647610799236e-15,
  'id_r2': 0.9999999999999936},
 {'gt_expression': '(-A + x1*y1 - x2*y2)/y3',
  'discovered_expression': 'x1 * y1 / y3 - (x2 * y2 + A) / y3',
  'id_mse': 5.714314873132767e-13,
  'id_nmse': 6.2241271577015845e-15,
  'id_r2': 0.9999999999999938},
 {'gt_expression': '(A + x2*y2 + x3*y3)/x1',
  'discovered_expression': '(A + x2 * y2 + x3 * y3) / x1',
  'id_mse': 9.934709168225883e-13,
  'id_nmse': 6.5514204941579835e-15,
  'id_r2': 0.9999999999999934},
 {'gt_expression': '(-A + x1*y1 - x3*y3)/x2',
  'discovered_expression': '(x1 * y1 - x3 * y3 - A) / x2',
  'id_mse': 5.679918148415428e-13,
  'id_nmse': 6.06727087639076e-15,
  'id_r2': 0.9999999999999939},
 {'gt_expression': '(-A + x1*y1 - x2*y2)/x3',
  'discovered_expression': '(x1 * y1 - A - x2 * y2) / x3',
  'id_mse': 5.809720552347479e-13,
  'id_nmse': 6.3262994221442655e-15,
  'id_r2': 0.9999999999999937},
 {'gt_expression': '-sqrt(q1*q2/(F*epsilon))/(2*sqrt(pi))',
  'discovered_expression': '-sqrt(q1 * q2 / (12.566370614359172 * epsilon * F))',
  'id_mse': 2.8549910431550674e-15,
  'id_nmse': 2.5136330366755035e-15,
  'id_r2': 0.9999999999999974},
 {'gt_expression': '-sqrt(q1/(Ef*epsilon))/(2*sqrt(pi))',
  'discovered_expression': '-sqrt(q1 / (12.566370614 * epsilon * Ef))',
  'id_mse': 2.27867294744235e-15,
  'id_nmse': 2.62495318878403e-15,
  'id_r2': 0.9999999999999973},
 {'gt_expression': '-c*p*sqrt(1/(c**2*m_0**2 + p**2))',
  'discovered_expression': '-1 / sqrt((m_0 / p) ** 2 + 1 / c ** 2)',
  'id_mse': 8.382128173587436e-15,
  'id_nmse': 5.6772493271833215e-15,
  'id_r2': 0.9999999999999943},
 {'gt_expression': 'sqrt(4*E_n/m - omega**2*x**2)/x',
  'discovered_expression': 'sqrt(E_n / m * 3.9999974 / x ** 1.9999981 - omega ** 2)',
  'id_mse': 5.780168591128743e-12,
  'id_nmse': 7.904069382790153e-13,
  'id_r2': 0.9999999999992096},
 {'gt_expression': 'd2/foc - d2/d1',
  'discovered_expression': 'd2 * (d1 - foc) / (foc * d1)',
  'id_mse': 4.01019230573258e-14,
  'id_nmse': 3.6601416178352545e-15,
  'id_r2': 0.9999999999999963},
 {'gt_expression': 'x2*cos(theta1 - theta2) - sqrt(x**2 + x2**2*cos(theta1 - theta2)**2 - x2**2)',
  'discovered_expression': 'x2 * cos(theta1 - theta2) - sqrt(abs(x ** 2 - x2 ** 2 * sin(theta1 - theta2) ** 2))',
  'id_mse': 1.6845435131815617e-13,
  'id_nmse': 1.501686643740824e-14,
  'id_r2': 0.999999999999985},
 {'gt_expression': 'x1*cos(theta1 - theta2) - sqrt(x**2 + x1**2*cos(theta1 - theta2)**2 - x1**2)',
  'discovered_expression': '(x1 ** 2 - x ** 2) / (x1 * cos(theta2 - theta1) + sqrt(x ** 2 - x1 ** 2 * sin(theta2 - theta1) ** 2))',
  'id_mse': 1.6845435124163323e-13,
  'id_nmse': 1.50168664305866e-14,
  'id_r2': 0.999999999999985},
 {'gt_expression': 'sqrt(3)*sqrt(Pwr/(c*epsilon))*(-omega**2 + omega_0**2)/(2*sqrt(pi)*Ef*omega**2)',
  'discovered_expression': 'sqrt(-39.373493745180106 * Pwr / (49.879432974818755 * -3.3065192522545863 * epsilon * c * Ef ** 2)) * abs(omega_0 ** 2 - omega ** 2) / omega ** 2',
  'id_mse': 1.4821226957205731e-12,
  'id_nmse': 2.4950217000221786e-14,
  'id_r2': 0.999999999999975},
 {'gt_expression': 'sqrt(6)*sqrt(pi)*sqrt(Pwr*c**3*epsilon)/a',
  'discovered_expression': 'sqrt(18.84955592153876 * epsilon * c ** 3 * Pwr) / a',
  'id_mse': 6.113441747415258e-12,
  'id_nmse': 6.835808210369742e-15,
  'id_r2': 0.9999999999999931},
 {'gt_expression': 'c*omega*sqrt(1 - v**2/c**2)/(c + v)',
  'discovered_expression': 'omega / sqrt(1 - (v / c) ** 2) - omega * v / c / sqrt(1 - (v / c) ** 2)',
  'id_mse': 3.341224503711402e-14,
  'id_nmse': 7.556102957771666e-15,
  'id_r2': 0.9999999999999925},
 {'gt_expression': 'omega*(c - v)/c',
  'discovered_expression': 'omega * (c - v) / c',
  'id_mse': 4.368002027284165e-14,
  'id_nmse': 7.423548995234065e-15,
  'id_r2': 0.9999999999999926},
 {'gt_expression': 'T*kb*log(n_0/n)/(m*x)',
  'discovered_expression': '1.0000000017925066 * kb * T / (m * x) * log(n_0 / n)',
  'id_mse': 2.438605598627472e-14,
  'id_nmse': 4.692690977700496e-15,
  'id_r2': 0.9999999999999953},
 {'gt_expression': '1 + kb*v/(A*kappa)',
  'discovered_expression': 'kb * v / (kappa * A) + 1',
  'id_mse': 7.273393864085201e-14,
  'id_nmse': 3.6227449264254954e-15,
  'id_r2': 0.9999999999999963},
 {'gt_expression': 'A*kappa*(gamma - 1)/kb',
  'discovered_expression': 'kappa / kb * (gamma - 1) * A',
  'id_mse': 3.3013335289656497e-12,
  'id_nmse': 7.361113848520866e-15,
  'id_r2': 0.9999999999999927}]

In [11]:
from bench_sr_agent import DATASET_SPLITS, load_problems, build_argparser

parser = build_argparser()
args, _ = parser.parse_known_args()

datasets = list(DATASET_SPLITS.keys())
problems = []
for dataset in datasets:
    problems.extend(load_problems(dataset, args.data_root))

In [14]:
problems[0]

Problem(dataset_identifier='lsrtransform', equation_idx='II.6.15b_1_0', symbols=['p_d', 'Ef', 'epsilon', 'theta', 'r'], symbol_descs=['the dipole moment', 'the electric field', 'the electric constant or permittivity of the medium', 'the angle between the dipole axis and the position vector', 'the distance from the dipole to the point where the electric field is being measured'], symbol_properties=['O', 'V', 'V', 'V', 'V'], expression='8*pi*Ef*epsilon*r**3/(3*sin(2*theta))', samples={'test': array([[-1.89978886e+01,  5.25637604e-02,  1.82653153e+00,
         2.89664268e+00,  2.23163176e+00],
       [-3.33039780e+01, -1.37035444e-01,  2.89017677e+00,
         1.25211060e+00,  1.81440020e+00],
       [-1.55860071e+01,  8.87142196e-02,  2.63639474e+00,
         2.06723142e+00,  1.88169527e+00],
       ...,
       [-7.01482487e+00,  1.20707955e-02,  2.59601259e+00,
         1.96577024e+00,  2.66748810e+00],
       [-2.04217935e+00, -3.72400843e-02,  1.98443580e+00,
         1.00902021e+00,  1.43809414e+00],
       [-1.63505459e+01, -6.81044385e-02,  1.16933548e+00,
         1.17541265e+00,  2.59239483e+00]], shape=(20000, 5)), 'train': array([[ 2.43452225e+01, -7.24347308e-02,  1.23010910e+00,
         2.66968441e+00,  2.97802305e+00],
       [ 2.33715572e+01,  8.99118707e-02,  2.21813297e+00,
         1.20959222e+00,  2.09908938e+00],
       [-1.18772745e+00,  2.82837935e-02,  1.26678193e+00,
         2.48928094e+00,  1.56289458e+00],
       ...,
       [ 6.85458755e+00, -7.04168305e-02,  1.16030550e+00,
         2.12546992e+00,  2.07751894e+00],
       [ 8.32945703e+03, -1.41441569e-01,  2.58052969e+00,
         1.57347536e+00,  2.44384480e+00],
       [-5.07489204e+01,  8.89461637e-02,  1.89850497e+00,
         2.87059665e+00,  2.64502048e+00]], shape=(80000, 5))}, desc=None)

In [30]:
import nd2py as nd
from tqdm import tqdm
from sr_agent.utils import symbolic_acc, setup_logging

setup_logging()


for idx, row in tqdm(df_results.iterrows(), total=len(df_results)):
    for problem in problems:
        if row['equation_id'] == problem.equation_idx:
            break
    else:
        raise ValueError(f"Problem with equation_id {row['equation_id']} not found in loaded problems.")
    
    f_true = nd.parse(row['gt_expression'])
    f_pred = nd.parse(row['discovered_expression'])
    data = {var: problem.samples['train'][:, idx] for idx, var in enumerate(problem.symbols)}
    result = symbolic_acc(f_true, f_pred, data)
    df_results.loc[idx, 'symbolic_acc'] = result['symbolic_acc']
    print(f"Problem ID: {row['equation_id']}, Symbolic Accuracy: {result['symbolic_acc']}, Reason: {result['reason']}")

AttributeError: 'OutStream' object has no attribute 'reconfigure'

In [29]:
f_true, f_pred

(-c * sqrt(1 - m_0 ** 2 / m ** 2), -c * sqrt(1 - (m_0 / m) ** 2))